name: agrotech_hackat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <4.0.0"


dependencies:
  flutter:
    sdk: flutter
  get:
  google_fonts: 6.1.0
  flutter_svg: 
  pin_code_text_field:
  http: ^1.2.0
  image_picker: ^1.0.8
  retrofit: ^4.1.0
  dio: ^5.4.3+1
  freezed_annotation:
  pretty_dio_logger: ^1.1.1
  flutter_screenutil: ^5.5.2
  flutter_easyloading:
  geocoding:
  geolocator:
  flutter_google_places_sdk: ^0.3.7
  permission_handler: ^11.3.1
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  get_storage:
  webview_flutter: ^4.0.1
  cupertino_icons: ^1.0.2
  firebase_database: ^10.2.2
  lottie: ^3.1.0
  location: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: null
  flutter_lints: ^3.0.2
  flutter_svg_opt: ^0.0.1
  build_runner: ^2.1.11
  retrofit_generator: ^8.1.0
  freezed: 
  json_serializable:
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/svgs/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  flutter_lints: ^1.0.0
